# reference: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
name: build image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build image
        run: |
          docker buildx build --push \
            --tag johntrimble/ext-mdns-over-host-avahi:latest \
            --platform linux/amd64,linux/arm64 .
